// This file is auto-generated by Ponder. Do not edit directly.
// Re-generate with `ponder codegen`.

declare module "ponder:registry" {
  import type { Virtual } from "ponder";
  type config = typeof import("./ponder.config.ts").default;
  type schema = typeof import("./ponder.schema.ts");
  export const ponder: Virtual.Registry<config, schema>;
}

declare module "ponder:schema" {
  export * from "./ponder.schema.ts";
}

declare module "ponder:api" {
  import type { Virtual } from "ponder";
  type schema = typeof import("./ponder.schema.ts");
  export const db: Virtual.Drizzle<schema>;
}
